FROM busybox:stable-musl AS downloader_extractor

ADD https://github.com/Oxen-AI/Oxen/releases/download/v0.15.16/oxen-server-ubuntu-latest.deb .
RUN ar x oxen-server-ubuntu-latest.deb && \
    tar xzf data.tar.gz

FROM gcr.io/distroless/cc-debian12
WORKDIR /bin
# Fallsback to in-memory 1st-party db
ENV REDIS_URL "redis://localhost:6379"
COPY --from=downloader_extractor /usr/bin/oxen-server .
EXPOSE 3000
ENTRYPOINT ["/bin/oxen-server", "start"]
