name: docker_build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      oxen_version: ${{ steps.version.outputs.oxen_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Modify Dockerfile with latest version
        id: version
        shell: bash
        run: |
          version="$(curl -s https://api.github.com/repos/Oxen-AI/Oxen/releases/latest | jq -r .tag_name)"
          # rather than pass in next `step` with `build-args` replace here:
          sed -i '/^ARG OXEN_VERSION=/c\ARG OXEN_VERSION='"$version" Dockerfile.distroless
          # Don't run next `step` if Dockerfile unchanged
          # git diff --exit-code Dockerfile.distroless >/dev/null && >&2 echo 'No Dockerfile changes made' && exit 3
          printf 'oxen_version=%s\n' "$version"

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            Dockerfile:
              - 'Dockerfile*'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
#        if: steps.changes.outputs.Dockerfile == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#        if: steps.changes.outputs.Dockerfile == 'true'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#        if: steps.changes.outputs.Dockerfile == 'true'

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.distroless
          tags: |
            samuelmarks/oxen-builds:distroless_cc-debian12_oxen_server_latest
            samuelmarks/oxen-builds:distroless_cc-debian12_oxen_server_${{ steps.version.outputs.oxen_version }}
#        if: steps.changes.outputs.Dockerfile == 'true'
