name: docker_build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Modify Dockerfile with latest version
        shell: bash
        run: |
          version="$(curl -s https://api.github.com/repos/Oxen-AI/Oxen/releases/latest | jq -r .tag_name)"
          # rather than pass in next `step` with `build-args` replace here:
          sed -i '/^ARG OXEN_VERSION=/c\ARG OXEN_VERSION='"$version" Dockerfile.distroless
          # Don't run next `step` if Dockerfile unchanged
          git diff --exit-code Dockerfile.distroless >/dev/null && >&2 echo 'No Dockerfile changes made' && exit 3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile.distroless
          tags: samuelmarks/oxen-builds:distroless_cc-debian12_oxen_server_latest
