name: schedule_oxen_pull

on:
  schedule:
    # 12:34AM every Thursday
    - cron:  '34 12 * * THU'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: oxen-builds

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Oxen-AI/Oxen
          path: oxen

      - name: Trigger other workflows by `push`ing a new `commit` on new release
        shell: bash
        run: |
          msg="$(GIT_DIR=oxen/.git git log -1 --pretty='format:%h\t%B')"
          cd oxen-builds
          if ! grep -qF "$version" 'RELEASE'; then
            version="$(curl -s https://api.github.com/repos/Oxen-AI/Oxen/releases/latest | jq -r .tag_name)"
            sed -i '/^ARG OXEN_VERSION=/c\ARG OXEN_VERSION='"$version" Dockerfile.distroless
            if ! git diff --exit-code Dockerfile.distroless >/dev/null; then
              printf '%s\n' "$msg" >> 'RELEASE'
              git commit -am "$msg"
              git push origin master
            fi
          fi
